== copyright-statement
=== {blank}
© {{ docyear }} The Calendaring and Scheduling Consortium, Inc. 

{% if unpublished %}
== license-statement
=== Warning for Drafts
This document is not a CalConnect Standard. It is distributed for review and
        comment, and is subject to change without notice and may not be referred to as
        a Standard. Recipients of this draft are invited to submit, with their
        comments, notification of any relevant patent rights of which they are aware
        and to provide supporting documentation.
{% endif %}

== legal-statement
=== {blank}
All rights reserved. Unless otherwise specified, no part of this
        publication may be reproduced or utilized otherwise in any form or by any
        means, electronic or mechanical, including photocopying, or posting on the
        internet or an intranet, without prior written permission. Permission can
        be requested from the address below. 

== feedback-statement
=== {blank}
[[boilerplate-name]]
The Calendaring and Scheduling Consortium, Inc.
[[boilerplate-address]]
4390 Chaffin Lane +
McKinleyville +
California 95519 +
United States of America +
 +
copyright@calconnect.org +
https://www.calconnect.org[www.calconnect.org]
